name: BuildContainerImage

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'release-*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'release-*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push docker images
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - name: Build and push docker images
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_AIL_USERNAME }}
          password: ${{ secrets.DOCKER_AIL_PASSWORD }}
        if: github.event_name == 'push'
        run: |
          REPO=wumingq TAG="${GITHUB_REF#refs/*/}" make container-cross-push
          REPO=registry.cn-hangzhou.aliyuncs.com/wumingq TAG="${GITHUB_REF#refs/*/}" make container-cross-push
      